### ISSUE TITLE
Add an option for saving cooldown

### ISSUE THREAD

**Issue by NoltoxGit** [iGabyTM/MasterCooldowns#7]
Hellow,
Would it be possible to add a new option to hide or set a delay for the `Saving x cooldown(s) to database.` message which is quite frequent in the console anyway?

Example:
```yml
  console:
      SendSavingMessages: true/false
      DelaySavingMessage: 5 #minutes
```
